// Generates src/icons.css: only the icons the app uses, as inline SVG masks.
// Why: the app used to load the whole Font Awesome font from a CDN. That is a third-party
// request on every visit (privacy + supply-chain risk), breaks offline, and blocks a strict
// Content-Security-Policy. This keeps the same class names (fa-solid fa-xmark ...) so no markup changes.
// Run after adding an icon:  node scripts/build-icons.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const ICONS = {
  solid: ['xmark', 'plus', 'trash-can', 'square-plus', 'download', 'chevron-right', 'chevron-left', 'upload', 'rotate',
    'pen-to-square', 'magnifying-glass', 'house', 'gear', 'check', 'calendar-days', 'arrow-up-from-bracket', 'shield-halved', 'user-xmark'],
  regular: ['calendar-xmark'],
  brands: ['google']
};
const base = new URL('../node_modules/@fortawesome/fontawesome-free/svgs/', import.meta.url);

let css = `/* GENERATED by scripts/build-icons.mjs. Do not edit by hand.
   Icons: Font Awesome Free (https://fontawesome.com), CC BY 4.0 license. */
.fa-solid, .fa-regular, .fa-brands {
  display: inline-block;
  width: 1em;
  height: 1em;
  vertical-align: -0.125em;
  background-color: currentColor;
  -webkit-mask: var(--icon) center / contain no-repeat;
  mask: var(--icon) center / contain no-repeat;
}
`;
for (const [style, names] of Object.entries(ICONS)) {
  for (const name of names) {
    const svg = readFileSync(new URL(`${style}/${name}.svg`, base), 'utf8')
      .replace(/<!--[\s\S]*?-->/g, '')          // license comment (credited above)
      .replace(/\s+/g, ' ').trim();
    if (!/^<svg[^>]*>.*<\/svg>$/.test(svg) || /<script|on\w+=|href=/i.test(svg)) throw new Error(`unexpected SVG content in ${style}/${name}`);
    const uri = 'data:image/svg+xml,' + encodeURIComponent(svg).replace(/%20/g, ' ').replace(/%3D/g, '=').replace(/%3A/g, ':').replace(/%2F/g, '/');
    css += `.fa-${style}.fa-${name} { --icon: url("${uri}"); }\n`;
  }
}
writeFileSync(new URL('../src/icons.css', import.meta.url), css);
console.log(`wrote src/icons.css: ${Object.values(ICONS).flat().length} icons, ${css.length} bytes`);
